### ISSUE TITLE
Add additional Cell.whenNext signature overload

### ISSUE THREAD

**Issue by amuttsch** [phaller/reactive-async#81]
Signature: `whenNext(dependecyCell, previousValue, callback)`

A callback that is called when the cell has a better value than `previousValue`. Same for `whenNextSequential`.

**Comment by JanKoelzer** [comment]
We have decided that the callback needs to be called for every other value than bottom, so it seems to me that this issue is superseded by #99 .
Anyway, its syntax would most probably clash with #87 so we need to rethink the syntax.
